version: '3'
services:
    nginx:
        image: nginx:stable-alpine
        restart: always
        ports:
            - "3000:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - node-app
    node-app:
        # Custom container name
        # container_name: node-app
        # image: node-app-image:tag
        restart: always
        image: livipst2/comic-node-app
        environment:
            - PORT=3000
        depends_on:
            - mongo
        # env_file:
        #     - ./.env
    mongo:
        image: mongo
        # Open port for outside connection
        ports:
            - "27012:27017"
        volumes:
            - mongo-db:/data/db
        
    redis:
        image: redis
        restart: always

# Named volumes
volumes:
    mongo-db: