version: '3'
services:
    nginx:
        ports:
            - "80:80"

    node-app:
        build:
            # Location of dockerFile
            context: .
            args:
                NODE_ENV: production
        environment:
            - NODE_ENV=production
            # Remove Later :x:
            - MONGO_USER=ducchuy
            - MONGO_PASSWORD=mypassword
            - WASABI_ACCESS_KEY_ID=NGAA0F53USVKDK1KHV0M,
            - WASABI_SECRET_ACCESS_KEY=MKCCJ0gCJ2YveUg2SYhtHUnj4HHgiS51vqZjGuBk,
            - WASABI_ENDPOINT= s3.eu-central-1.wasabisys.com,
            - WASABI_BUCKET_NAME= cloudimagewallbucket,
            - WASABI_REGION= eu-central-1,
        command: node ./src/index.js
    mongo:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=ducchuy
            - MONGO_INITDB_ROOT_PASSWORD=mypassword
    mongo_seed:
        image: mongo
        links:
            - mongo
        depends_on:
            - mongo
        volumes:
            - ./mongo-seed:/mongo-seed
        command:
            /mongo-seed/import.sh