version: '3'
services:
    nginx:
        image: nginx:stable-alpine
        restart: always
        volumes:
            - ./etc/nginx/defaultDev.conf:/etc/nginx/conf.d/default.conf
            - ./etc/certs:/etc/nginx/certs:ro
        depends_on:
            - node-app
    node-app:
        # Custom container name
        # container_name: node-app
        # image: node-app-image:tag
        restart: always
        image: livipst2/comic-node-app
        depends_on:
            - mongo
            - redis
        # env_file:
        #     - ./.env
    mongo:
        image: mongo
        # Open port for outside connection
        ports:
            - "27012:27017"
        command: mongod --auth
        volumes:
            - mongo-db:/data/db
            # - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    mongo_seed:
        image: mongo
        links:
            - mongo
        depends_on:
            - mongo
        volumes:
            - ./mongo-seed:/mongo-seed
        command:
            /mongo-seed/import.sh
        depends_on:
            - mongo
    redis:
        image: redis
        restart: always

# Named volumes
volumes:
    mongo-db: