version: '3'
services:
    nginx:
        ports:
            - "80:80"

    node-app:
        build:
            # Location of dockerFile
            context: .
            args:
                NODE_ENV: production
        environment:
            - NODE_ENV=production
            # Remove Later :x:
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASSWORD=mypassword${MONGO_PASSWORD}
            - WASABI_ACCESS_KEY_ID=${WASABI_ACCESS_KEY_ID}
            - WASABI_SECRET_ACCESS_KEY=${WASABI_SECRET_ACCESS_KEY}
            - WASABI_ENDPOINT=s3.eu-central-1.wasabisys.com
            - WASABI_BUCKET_NAME=cloudimagewallbucket
            - WASABI_REGION=eu-central-1
        command: node ./src/index.js
    mongo:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}