version: '3'
services:
    nginx:
        ports:
            - "80:80"
            - "443:443"
    node-app:
        build:
            # Location of dockerFile
            context: .
            args:
                NODE_ENV: production
        environment:
            - NODE_ENV=production
            # Remove Later :x:
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
            - WASABI_ACCESS_KEY_ID=${WASABI_ACCESS_KEY_ID}
            - WASABI_SECRET_ACCESS_KEY=${WASABI_SECRET_ACCESS_KEY}
            - WASABI_BUCKET_NAME=${WASABI_BUCKET_NAME}
            - WASABI_ENDPOINT=${WASABI_ENDPOINT}
            - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
            - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
            - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
            - IMAGE_URL=${IMAGE_URL}
        command: node ./src/index.js
    mongo:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}