version: '3'
services:
    nginx:
        ports:
            - "3000:80"
    node-app:
        build:
            # Location of dockerFile
            context: .
            args:
                NODE_ENV: development
        volumes:
            - ./:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - MONGO_USER=ducchuy
            - MONGO_PASSWORD=mypassword
        command: npm start
    